apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colors-staging
spec:
  project: default
  source:
    path: manifests/colors/staging
    repoURL: 'https://github.com/todaywasawesome/oss-apps.git'
    targetRevision: HEAD
  destination:
    name: oss-staging
    namespace: colors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false