apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-1
spec:
  project: default
  source:
    path: examples/demo-app
    repoURL: https://github.com/argoproj-labs/argocd-autopilot/
    targetRevision: HEAD
  destination:
    name: oss-staging
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
